import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./componentSets/header/header.js";
import Footer from "./componentSets/footer/footer.js";
import ContactForm from "./components/form/form.js";
import Specialists from "./componentSets/specialists/specialists.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Papuzka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>{children}
      <Specialists/>
      <ContactForm/>
      <Footer/>
      </body>
    </html>
  );
}
