import { Inter } from "next/font/google";
import "./globals.css";
/* import Header from "./component sets/header/header.js"; */
import Header from "./componentSets/header/header";
import Footer from "./componentSets/footer/footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Papuzka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>{children}
      <Footer/>
      </body>
    </html>
  );
}
